spring:
  datasource:
    url: jdbc:mysql://172.16.0.6:1124/dynamic_route?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #最小，最大，初始化大小
      min-idle: 8
      max-active: 24
      initial-size: 8
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-timeMillis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      show-sql: true
      format-sql: false
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      cache:
        use_second_level_cache: false
        use_query_cache: false

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,info
        
swagger:
  contact:
    name: SortfGrowingup
    url: http://www.alonexplore.com/
    email: 199784567@qq.com
  enabled: true
  title: 文章相关API
  version: 1.0
  description: 接口前面统一添加 '/route' 路径
  base-path: /**
  base-package: com.nimblecloud.article.controller
  exclude-path: /error
  host: localhost:301